framework:
    asset_mapper:
        public_prefix: 'assets/'
        importmap_polyfill: false
        # Dossier scanné pour les fichiers gérés par AssetMapper (JS/CSS)
        paths:
            - assets/
                # Extensions gérées (inclure images et styles)
        extensions: [ 'js', 'css', 'png', 'jpg', 'jpeg', 'gif', 'svg', 'webp' ]

when@prod:
    framework:
        asset_mapper:
            missing_import_mode: warn
